//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net.Pranas.Client.GoogleDrive.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Net.Pranas.Client.GoogleDrive.Resources.LocalStrings", typeof(LocalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &quot;{0}&quot; cannot be null or empty..
        /// </summary>
        internal static string ArgumentNullOrEmptyErrorMessage1 {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmptyErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Drive authentication failed..
        /// </summary>
        internal static string AuthenticationErrorMessage {
            get {
                return ResourceManager.GetString("AuthenticationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response status code. All file data was sent successfully, but did not get response with &quot;{0}&quot; or &quot;{1}&quot; status code..
        /// </summary>
        internal static string ChunkUploadInvalidLastStatusCodeErrorMessage2 {
            get {
                return ResourceManager.GetString("ChunkUploadInvalidLastStatusCodeErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response header. Location header does not exist..
        /// </summary>
        internal static string LocationHeaderNotExistsMessage {
            get {
                return ResourceManager.GetString("LocationHeaderNotExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response header. Failed to read end of range as a numeric value. Range header: &quot;{0}&quot;..
        /// </summary>
        internal static string RangeHeaderInvalidEndErrorMessage1 {
            get {
                return ResourceManager.GetString("RangeHeaderInvalidEndErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response header. Failed to read range value as a numeric range. Range header: &quot;{0}&quot;..
        /// </summary>
        internal static string RangeHeaderInvalidErrorMessage1 {
            get {
                return ResourceManager.GetString("RangeHeaderInvalidErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response header. Range header does not exist..
        /// </summary>
        internal static string RangeHeaderNotExistErrorMessage {
            get {
                return ResourceManager.GetString("RangeHeaderNotExistErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request body is null..
        /// </summary>
        internal static string RequestBodyNullReferenceErrorMessage {
            get {
                return ResourceManager.GetString("RequestBodyNullReferenceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response by the request &quot;{0}&quot; is null..
        /// </summary>
        internal static string ResponseNullReferenceErrorMessage1 {
            get {
                return ResourceManager.GetString("ResponseNullReferenceErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected response status code &quot;{0}&quot;. Status description: &quot;{1}&quot;..
        /// </summary>
        internal static string ResponseStatusCodeUnexpectedErrorMessage2 {
            get {
                return ResourceManager.GetString("ResponseStatusCodeUnexpectedErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is null..
        /// </summary>
        internal static string TokenNullReferenceErrorMessage {
            get {
                return ResourceManager.GetString("TokenNullReferenceErrorMessage", resourceCulture);
            }
        }
    }
}
